# Parámetros básicos del servidor
quarkus.http.host=0.0.0.0
quarkus.http.port=8080
quarkus.http.idle-timeout=30S

# Observabilidad: Health checks
quarkus.smallrye-health.enabled=true
quarkus.smallrye-health.root-path=/q/health

# Observabilidad: Métricas Prometheus
quarkus.micrometer.enabled=true
quarkus.micrometer.export.prometheus.enabled=true
quarkus.micrometer.export.prometheus.path=/metrics

quarkus.datasource.db-kind=mysql
quarkus.datasource.username=quarkus_user
quarkus.datasource.password=itq01
# Importante: Usa 127.0.0.1 en lugar de localhost para forzar TCP
quarkus.datasource.jdbc.url=jdbc:mysql://127.0.0.1:3306/ecommerce_db
